# Generated by Django 5.0.9 on 2026-09-04 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Mô tả ngắn"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Ảnh banner"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Đường dẫn khi bấm vào"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        default="Xem ngay",
                        max_length=60,
                        verbose_name="Chữ trên nút",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "Slider trang chủ"),
                            ("sidebar", "Cột bên"),
                            ("footer", "Chân trang"),
                        ],
                        default="hero",
                        max_length=20,
                        verbose_name="Vị trí",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Thứ tự"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Bắt đầu hiển thị",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kết thúc hiển thị"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hiển thị"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banner",
                "ordering": ["display_order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=280,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Tóm tắt"
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Thẻ (phân cách bằng dấu phẩy)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Đã xuất bản"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày xuất bản"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lượt xem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tác giả",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin tức",
                "verbose_name_plural": "Tin tức",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tên chương trình"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=280,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="promotions/",
                        verbose_name="Ảnh chương trình",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Giảm giá (%)"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Bắt đầu"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Kết thúc")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang chạy"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotions",
                        to="catalog.product",
                        verbose_name="Sản phẩm áp dụng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khuyến mãi",
                "verbose_name_plural": "Khuyến mãi",
                "ordering": ["-start_date"],
            },
        ),
    ]
