# Generated by Django 5.0.9 on 2026-09-04 02:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(max_length=60, unique=True, verbose_name="Mã lô"),
                ),
                (
                    "quantity_in",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Số lượng nhập",
                    ),
                ),
                (
                    "quantity_remaining",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng còn lại"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giá vốn / đơn vị",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Ngày nhập kho",
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày sản xuất"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Dùng để cảnh báo lô hàng sắp hết hạn",
                        null=True,
                        verbose_name="Hạn sử dụng / hết bảo hành lô",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="catalog.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="catalog.supplier",
                        verbose_name="Nhà cung cấp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lô hàng",
                "verbose_name_plural": "Lô hàng",
                "ordering": ["expiry_date", "received_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Nhập kho"),
                            ("out", "Xuất kho (bán hàng)"),
                            ("return", "Hoàn trả (hủy đơn)"),
                            ("adjust", "Điều chỉnh thủ công"),
                        ],
                        max_length=10,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Dương = tăng tồn, âm = giảm tồn",
                        verbose_name="Số lượng",
                    ),
                ),
                (
                    "quantity_after",
                    models.IntegerField(default=0, verbose_name="Tồn lô sau giao dịch"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chứng từ liên quan"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời điểm"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.batch",
                        verbose_name="Lô hàng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="catalog.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch kho",
                "verbose_name_plural": "Giao dịch kho",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["product", "quantity_remaining"],
                name="inventory_b_product_51df3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product", "-created_at"], name="inventory_s_product_6d60d9_idx"
            ),
        ),
    ]
