# Generated by Django 5.0.9 on 2026-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "ordering": ["received_date", "id"],
                "verbose_name": "Lô hàng",
                "verbose_name_plural": "Lô hàng",
            },
        ),
        migrations.RemoveField(
            model_name="batch",
            name="expiry_date",
        ),
    ]
