# Generated by Django 5.0.9 on 2026-09-04 02:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Tên thương hiệu"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/", verbose_name="Logo"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Quốc gia"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Thương hiệu",
                "verbose_name_plural": "Thương hiệu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, verbose_name="Tên nhà cung cấp"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Người liên hệ"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="suppliers/",
                        verbose_name="Logo",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hợp tác"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Nhà cung cấp",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Tên danh mục")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Ảnh",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Icon (emoji hoặc tên icon)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Danh mục cha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên sản phẩm")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=280,
                        unique=True,
                        verbose_name="Đường dẫn",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=60, unique=True, verbose_name="Mã SKU"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Mô tả ngắn"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả chi tiết"),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True,
                        help_text="Mỗi dòng một thông số theo dạng: Tên thông số: Giá trị",
                        verbose_name="Thông số kỹ thuật",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Để trống nếu không giảm giá",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giá khuyến mãi",
                    ),
                ),
                (
                    "warranty_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Bảo hành (tháng)"
                    ),
                ),
                (
                    "weight_gram",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Khối lượng (gram)"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang kinh doanh"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Sản phẩm nổi bật"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lượt xem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="Thương hiệu",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.supplier",
                        verbose_name="Nhà cung cấp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="Ảnh")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mô tả ảnh"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Thứ tự"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh sản phẩm",
                "verbose_name_plural": "Ảnh sản phẩm",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Số sao",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tiêu đề"
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Đã duyệt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đánh giá"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đánh giá",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="unique_review_per_user_product"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="catalog_pro_is_acti_e6e001_idx",
            ),
        ),
    ]
